name: ufdtd-c
channels:
  - conda-forge
  - nodefaults
dependencies:
  - gcc=15.2
  - gcc_win-64=15.2
  - emscripten=3.1.58
  - cmake>=4.4,<5
  - ninja>=1.13,<2
  - msmpi=10.1.1
  - python=3.12
  - numpy>=2.5,<3
  - matplotlib>=3.11,<4
  - pillow>=12,<13
  - pytest>=9,<10
  - tk>=8.6,<9
